site_name: BigML Secure API Docs
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.copybutton


nav:
  - Home: index.md
  - Authentication: authentication.md
  - Credential Management: credential-management.md
  - Access Control: access-control.md
  - Deployment & Monitoring: deployment-monitoring.md
  - Examples: examples.md
  - FAQ: faq.md
