site_name: BigML Secure API Docs
theme:
  name: material
markdown_extensions:
  - pymdownx.copybutton:
      copy_button_selector: "div.highlight pre"
      tooltip_text: "Copy to clipboard"
      tooltip_duration: 1000


nav:
  - Home: index.md
  - Authentication: authentication.md
  - Credential Management: credential-management.md
  - Access Control: access-control.md
  - Deployment & Monitoring: deployment-monitoring.md
  - Examples: examples.md
  - FAQ: faq.md
